"""
Library:      lib_bejson_errors.py
Family:       Core
Status:       OFFICIAL
Author:       Elton Boehnen
Version:      2.0.1 OFFICIAL
Description:  Unified error registry for BEJSON ecosystem.
"""

# BEJSON Core/Validator (1-29)
E_INVALID_JSON = 1
E_MISSING_MANDATORY_KEY = 2
E_INVALID_FORMAT = 3
E_INVALID_VERSION = 4
E_INVALID_RECORDS_TYPE = 5
E_INVALID_FIELDS = 6
E_INVALID_VALUES = 7
E_TYPE_MISMATCH = 8
E_RECORD_LENGTH_MISMATCH = 9
E_RESERVED_KEY_COLLISION = 10
E_INVALID_RECORD_TYPE_PARENT = 11
E_NULL_VIOLATION = 12
E_FILE_NOT_FOUND = 13
E_PERMISSION_DENIED = 14
E_ATOMIC_WRITE_FAILED = 15

E_CORE_INVALID_VERSION = 20
E_CORE_INVALID_OPERATION = 21
E_CORE_INDEX_OUT_OF_BOUNDS = 22
E_CORE_FIELD_NOT_FOUND = 23
E_CORE_TYPE_CONVERSION_FAILED = 24
E_CORE_BACKUP_FAILED = 25
E_CORE_WRITE_FAILED = 26
E_CORE_QUERY_FAILED = 27
E_CORE_ENCRYPTION_FAILED = 28
E_CORE_DECRYPTION_FAILED = 29

# MFDB Core/Validator (30-49)
E_MFDB_NOT_MANIFEST = 30
E_MFDB_NOT_ENTITY_FILE = 31
E_MFDB_MANIFEST_RECORDS_TYPE = 32
E_MFDB_ENTITY_NOT_FOUND = 33
E_MFDB_ENTITY_NAME_MISMATCH = 34
E_MFDB_DUPLICATE_ENTRY = 35
E_MFDB_NO_PARENT_HIERARCHY = 36
E_MFDB_MANIFEST_NOT_FOUND = 37
E_MFDB_BIDIRECTIONAL_FAIL = 38
E_MFDB_FK_UNRESOLVED = 39
E_MFDB_MISSING_REQUIRED_FIELD = 40
E_MFDB_NULL_REQUIRED = 41
E_MFDB_INVALID_ARCHIVE = 42

E_MFDB_CORE_MANIFEST_NOT_FOUND = 50
E_MFDB_CORE_ENTITY_NOT_FOUND = 51
E_MFDB_CORE_WRITE_FAILED = 52
E_MFDB_CORE_CREATE_FAILED = 53
E_MFDB_CORE_INVALID_OPERATION = 54
E_MFDB_CORE_INDEX_OUT_OF_BOUNDS = 55
E_MFDB_CORE_JOIN_FAILED = 56
E_MFDB_CORE_ARCHIVE_ERROR = 70
E_MFDB_CORE_MOUNT_CONFLICT = 71

# Cognition (270-289)
E_COGNITION_INVALID_MATRIX = 270
E_COGNITION_AGENT_NOT_FOUND = 271
E_COGNITION_INDEX_MISSING = 272
E_COGNITION_PATCH_FAILED = 273
E_COGNITION_SCHEMA_VIOLATION = 274
E_COGNITION_LOCK_TIMEOUT = 275
